#!/usr/bin/env bash
# Exit on all errors and undefined vars
set -o errexit
set -o errtrace
set -o pipefail
set -o nounset

# enable globs
shopt -s globstar

doc() {
    cat <<-EOF
Runs the Unipipe pipeline dsl

USAGE:
  unipipe [command]

COMMANDS:
  transform [path osb-repo] [path out-repo]: transform a repository
  help: show this help text

EXAMPLES:
  unipipe transform 
    
EOF
}

dhall_dir=$(dirname "$0")

transform() {
  local dir_osb="$1"
  local dir_out="$2"

  # loop over all instance.yml files
  echo "Transforming service instances in $dir_osb"
  for filename in "$dir_osb"/instances/*/instance.yml; do
    echo "- processing $filename"

    # Parse yml to dhall so we work with it. We use the following options for parsing
    # --records-loose: ignore yml fields that are not specified in dhall, allowing us to only work with a well-known 
    #                  subset of properties in dhall and ignoring everything else.
    
    local instance_dhall
    instance_dhall="$(yaml-to-dhall --records-loose "$dhall_dir"/OSB/ServiceInstance.dhall < "$filename")"
    
    ## Execute the handler to determine the action to take

    dhall to-directory-tree --output "$dir_out" <<< "$dhall_dir/runner.dhall $instance_dhall"
    
    ## Execute the handler action
  done
}

main() {
  local cmd
  cmd="$1"

  case $cmd in
    help)
      doc
    ;;
    transform)
      transform "${@:2}"
    ;;
    *)
      echo "Unknown command '$cmd'. Use help to display help text."
      exit 1;
    ;;
  esac

  exit 0;
}

if [[ $# == 0 ]]; then
  echo "No command specified. Use help to display help text." 
  exit 1;
else
  main "$@"
fi


